name: "Auto merge PRs"

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix conflicts
        continue-on-error: true
        run: |
          git config user.name "{{ github.actor.name }}"
          git config user.email "{{ github.actor.email }}"
          git merge origin/main
          # Las siguientes lineas pueden entregar código
          # distinto a 0 si no hay nada que commitear.
          git commit -m "merge"
          git push

      - name: Merge PR
        continue-on-error: true
        run: gh pr merge $PR_NUMBER --merge
        env:
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
